# Generated by Django 4.2.3 on 2023-07-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='savat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.car'),
        ),
    ]
